- name: install
  apt:
    name: haproxy
    update_cache: yes

- name: enable
  service:
    name: haproxy
    state: started
    enabled: yes

- name: configure
  template:
    src: templates/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    validate: haproxy -c -f %s
  notify:
    haproxy_restart
