--- 
forwarders:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.10
localnets:
  - 192.168.56.0/24
  - 10.0.2.0/24
  - localhost
records:
  - type: NS
    entries:
      - name: meo.ttu.
        address: infra01.meo.ttu.
        name: meo.ttu.
        address: infra02.meo.ttu.
  - type: A
    entries:
      - name: infra01.meo.ttu.
        address: 192.168.56.4
      - name: infra02.meo.ttu.
        address: 192.168.56.5
      - name: infra.meo.ttu.
        addresses:
          - 192.168.56.4
          - 192.168.56.5
  - type: CNAME
    entries:
      - name: ns
        address: infra
      - name: ns1
        address: infra01
      - name: ns2
        address: infra02
      - name: web
        address: infra02
      - name: grafana
        address: infra01
      - name: prometheus
        address: infra01
      - name: influxdb
        address: infra02
