- name: Check if prometheus already exists
  stat:
    path: /opt/prometheus-2.14.0.linux-amd64.tar.gz
  register: stat_result

- name: Download
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.14.0/prometheus-2.14.0.linux-amd64.tar.gz
    dest: /opt/prometheus-2.14.0.linux-amd64.tar.gz
  when: stat_result.stat.exists == False

- name: folder
  file:
    path: /opt/prometheus
    state: directory
    mode: '0755'

- name: untar
  unarchive:
    src: /opt/prometheus-2.14.0.linux-amd64.tar.gz
    dest: /opt/prometheus
    remote_src: yes
    extra_opts:
      - --strip-components=1    
 
- name: config prometheus
  template:
    src: prometheus.yml.j2
    dest: /opt/prometheus/prometheus.yml
  notify:
    - restart prometheus

- name: make prometheus a service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify:
    - restart systemd

- name: start prometheus
  service:
    name: prometheus
    state: started
    enabled: yes
