- name: install prometheus
  apt:
    name: prometheus
#    update_cache: yes
    force_apt_get: yes
  tags:
    - p

- name: config prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify:
    - restart prometheus

- name: make prometheus a service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify:
    - restart systemd

- name: start prometheus
  service:
    name: prometheus
    state: started
    enabled: yes
