- name: daemon reload
  shell: "systemctl daemon-reload"

- name: restart mysql
  shell: "systemctl restart mysql"

- name: restart mysqld exporter
  shell: " systemctl restart prometheus-mysqld-exporter"
