- name: create backup user
  user:
    name: b4ckup
    generate_ssh_key: yes

- name: create directory
  file:
    path: /home/b4ckup/.ssh
    state: directory
    mode: '0755'

- name: upload key pair
  copy:
    src: "{{ item }}"
    dest: /home/b4ckup/.ssh/
  with_items:
    - templates/id_rsa
    - templates/id_rsa.pub

- name: upload mysqldump cnf file
  template:
    src: templates/.my.cnf.j2
    dest: /home/b4ckup/.my.cnf
    owner: b4ckup
  when: role == "mysql"
        
- name: mysql backup script
  template:
    src: templates/mysql.sh.j2
    dest: /home/b4ckup/mysql.sh
    owner: b4ckup
    mode: a+x
  when: role == "mysql"
  
- name: cron job for mysql
  cron:
    name: "backup mysql"
    minute: "0"
    hour: "0"
    user: b4ckup
    job: "/home/b4ckup/mysql.sh"
  when: role == "mysql"

- name: bind backup script
  copy:
    src: templates/bind.sh
    dest: /home/b4ckup/bind.sh
    owner: b4ckup
    mode: a+x
  when: dns_role == "master"

- name: cron job for bind
  cron:
    name: "backup bind"
    minute: "0"
    hour: "0"
    user: b4ckup
    job: "/home/b4ckup/bind.sh"
  when: dns_role == "master"

- name: wordpress backup script
  copy:
    src: templates/wordpress.sh
    dest: /home/b4ckup/wordpress.sh
    owner: b4ckup
    mode: a+x
  when: role == "wordpress"

- name: cron job for wordpress
  cron:
    name: "backup wordpress"
    minute: "0"
    hour: "0"
    user: b4ckup
    job: "/home/b4ckup/wordpress.sh"
  when: role == "wordpress"

