---
- name: node_exporter
  hosts: linux
  become: yes
  roles:
    - {role: 'bind', tags: 'bind'}
    - node_exporter

- name: mysql exporter
  hosts: mysql
  become: yes
  roles:
    - mysqld_exporter
  
- name: apache
  hosts: wordpress
  become: yes
  roles:  
    - apache_exporter

- name: prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus
    - grafana
