---
- name: init
  become: yes
  hosts: linux_legacy
  roles:
    - init
  tags:
    - init 

- name: bind
  become: yes
  hosts: linux
  roles:
    - bind
  tags:
    - bind

- name: influx
  become: yes
  hosts: influx
  roles:
    - influxdb
  tags:
    - influxdb

- name: grafana
  become: yes
  hosts: infra01
  roles:
    - grafana
  tags:
    - grafana
