- name: install docker
  apt:
    name: docker.io
    update_cache: yes
    state: present

- name: install pip
  apt:
    name: python3-pip

- name: install docker-py
  pip:
    name: docker-py

- name: start wordpress instance 1
  docker_container:
    name: wp1
    image: wordpress
    state: started
    ports:
      - "8080:80"
    env:
      WORDPRESS_DB_HOST: 192.168.56.5:3306
      WORDPRESS_DB_NAME: "{{ db }}"
      WORDPRESS_DB_USER: "{{ db_user }}"
      WORDPRESS_DB_PASSWORD: "{{ db_password }}"

- name: start wordpress instance 2
  docker_container:
    name: wp2
    image: wordpress
    state: started
    ports:
      - "8081:80"
    env:
      WORDPRESS_DB_HOST: 192.168.56.5:3306
      WORDPRESS_DB_NAME: "{{ db }}"
      WORDPRESS_DB_USER: "{{ db_user }}"
      WORDPRESS_DB_PASSWORD: "{{ db_password }}"
