- name: check if bind exporter exists
  stat:
    path: /opt/bind_exporter-v0.2.0-dev.tar.gz
  register: stat_result

- name: download
  get_url:
    url: https://github.com/digitalocean/bind_exporter/archive/v0.2.0-dev.tar.gz
    dest: /opt/
  when: stat_result.stat.exists == False

- name: folder
  file:
    path: /opt/bind_exporter
    state: directory
    mode: '0755'

- name: untar
  unarchive:
    src: /opt/bind_exporter-0.2.0-dev.tar.gz
    dest: /opt/bind_exporter
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: systemd bind_exporter
  template:
    src: bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service
  notify:
    - daemon reload

- name: start exporter
  service:
    name: bind_exporter
    state: started
    enabled: yes
