---
- name: First play
  hosts: 127.0.0.1
  remote_user: kat
  become: yes
  tasks:
  - name: First task
    ping:
    
  - name: Show proc list
    command: 'ps'
    register: abc

  - name: Show output
    debug:
      var: abc.stdout_lines

  - name: Set ssh
    authorized_key:    
      user: kat
      state: present
      key: "{{ lookup('file', '/home/kat/.ssh/id_rsa.pub') }}"

  - name: Disable sudo pass
    copy:
      dest: /etc/sudoers.d/user
      content: "kat   ALL = NOPASSWD: ALL"
