- name: check if apache exporter exists
  stat:
    path: /opt/apache_exporter-0.7.0.linux-amd64.tar.gz
  register: stat_result

- name: download
  get_url:
    url: https://github.com/Lusitaniae/apache_exporter/releases/download/v0.7.0/apache_exporter-0.7.0.linux-amd64.tar.gz
    dest: /opt/
  when: stat_result.stat.exists == False

- name: folder
  file:
    path: /opt/apache_exporter
    state: directory
    mode: '0755'

- name: untar
  unarchive:
    src: /opt/apache_exporter-0.7.0.linux-amd64.tar.gz
    dest: /opt/apache_exporter
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: systemd apache_exporter
  template:
    src: apache_exporter.service.j2
    dest: /etc/systemd/system/apache_exporter.service
  notify:
    - daemon reload

- name: start exporter
  service:
    name: apache_exporter
    state: started
    enabled: yes
