- name: install node exporter
  apt:
    name: prometheus-node-exporter
    force_apt_get: yes

#- name: make node exporter a service
#  template:
#    src: node_exporter.service.j2
#    dest: /etc/systemd/system/node_exporter.service

- name: restart exporter
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
