- name: make node exporter a service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: start exporter
  service:
    name: node_exporter
    state: started
    enabled: yes
