- name: install mysql server
  apt:
    name: mysql-server
    state: present
    update_cache: yes
    force_apt_get: yes

- name: install pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes
    force_apt_get: yes

- name: install PyMySQL
  pip:
    name: PyMySQL

- name: update mysql cnf
  copy:
    src: templates/mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
    - reload mysql
      
- name: create mysql user
  mysql_user:
    name: "{{ db_user }}"
    host: 192.168.56.4
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  ignore_errors: yes

- name: Create mysql database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock 
    name: "{{ db }}"
    state: present
