---  
- name: bind and node_exporter
  hosts: linux
  become: yes
  roles:
    - bind
    - node_exporter

- name: mysql exporter
  hosts: mysql
  become: yes
  roles:
    - mysqld_exporter
  tags:
    - mysqld 

- name: mysql_exporter
  hosts: prometheus 
  become: yes
  roles:
    - {role: prometheus, tags: prometheus}
    - apache_exporter
    - grafana
