---  
- name: bind and node_exporter
  hosts: linux
  become: yes
  roles:
    - bind
    - { role: node_exporter, tags: node }

- name: mysql exporter
  hosts: mysql
  become: yes
  roles:
    - mysqld_exporter
  tags:
    - mysqld 

- name: apache exporter
  hosts: wordpress
  become: yes
  roles:
    - apache_exporter
  tags:
    - apache 

- name: 
  hosts: prometheus 
  become: yes
  roles:
    - {role: prometheus, tags: prometheus}
    - {role: grafana, tags: grafana}
